spring.application.name=back
server.port=8080

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.mapper-locations=classpath:mapper/*.xml

openai.api.key=${OPENAI_API_KEY}

naver.client.id=${NAVER_CLIENT_ID}
naver.client.secret=${NAVER_CLIENT_SECRET}

savings.tier.silver-threshold=0.10
savings.tier.gold-threshold=0.25
savings.tier.platinum-threshold=0.40
